### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [8]:
import numpy as np

# Створення вектора з випадковими дійсними значеннями в діапазоні від 0 до 1
vector = np.random.rand(10)

# Створення матриці 3x3 з заданими значеннями
matrix = np.array([[1, 1, 20],
                  [29, 14, 23],
                  [32, 17, 26]])

# Виведення вектора, матриці та їхніх розмірностей
print("Вектор:")
print(vector)
print("Розмірність вектора:", vector.shape)

print("\nМатриця:")
print(matrix)
print("Розмірність матриці:", matrix.shape)

Вектор:
[0.94383265 0.16513354 0.8510505  0.53493263 0.59766075 0.36934428
 0.04070677 0.60488263 0.7712103  0.45187662]
Розмірність вектора: (10,)

Матриця:
[[ 1  1 20]
 [29 14 23]
 [32 17 26]]
Розмірність матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [9]:
# Додавання числа 10 до кожного значення вектора та округлення до 2 знаків після коми
vector_plus_10 = np.round(vector + 10, 2)

# Помноження кожного елементу матриці на 2
matrix_times_2 = matrix * 2

# Створення нового вектора, який містить квадрат кожного значення vector
vector_squared = np.square(vector)

# Виведення результатів на екран
print("Вектор після додавання числа 10 та округлення до 2 знаків після коми:")
print(vector_plus_10)

print("\nМатриця після множення кожного елементу на 2:")
print(matrix_times_2)

print("\nНовий вектор, який містить квадрат кожного значення вектора:")
print(vector_squared)

Вектор після додавання числа 10 та округлення до 2 знаків після коми:
[10.94 10.17 10.85 10.53 10.6  10.37 10.04 10.6  10.77 10.45]

Матриця після множення кожного елементу на 2:
[[ 2  2 40]
 [58 28 46]
 [64 34 52]]

Новий вектор, який містить квадрат кожного значення вектора:
[0.89082006 0.02726909 0.72428696 0.28615292 0.35719837 0.1364152
 0.00165704 0.365883   0.59476533 0.20419248]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [10]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [32]:
# Множення матриць A і B
result_matrix = np.dot(A, B)

print("Результат множення матриць A і B:")
print(result_matrix)

Результат множення матриць A і B:
[[0.232  0.1627 0.2145]
 [0.3061 0.4867 0.633 ]
 [0.1393 0.2261 0.294 ]]


In [51]:
# Множення результуючої матриці на вектор C
result_vector_C = np.dot(result_matrix[:, :2], C)

# Виведення результату
print("\nРезультат множення результуючої матриці на вектор C:")
print(result_vector_C)


Результат множення результуючої матриці на вектор C:
[[0.1627]
 [0.4867]
 [0.2261]]


In [52]:
# Відфільтруємо перші дві колонки result_matrix для множення на D
result_matrix_filtered = result_matrix[:, :2]

# Множення result_matrix_filtered на матрицю D
result_matrix_D = np.dot(result_matrix_filtered, D)

# Виведення результату
print("\nРезультуюча матриця result_matrix_D:")
print(result_matrix_D)


Результуюча матриця result_matrix_D:
[[0.1627 0.232 ]
 [0.4867 0.3061]
 [0.2261 0.1393]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [53]:
# Транспонування result_matrix
transposed_result_matrix = result_matrix.T

# Виведення форми транспонованої матриці
print("Форма транспонованої матриці:", transposed_result_matrix.shape)

# Транспонування вектора vector
transposed_vector = vector.T

# Виведення форми транспонованого вектора
print("Форма транспонованого вектора:", transposed_vector.shape)

# Використання операції numpy.expand_dims для створення стовпчикового вектора
column_vector = np.expand_dims(vector, axis=1)

# Виведення форми стовпчикового вектора
print("Форма стовпчикового вектора:", column_vector.shape)

# Транспонування стовпчикового вектора
transposed_column_vector = column_vector.T

# Виведення форми транспонованого стовпчикового вектора
print("Форма транспонованого стовпчикового вектора:", transposed_column_vector.shape)

Форма транспонованої матриці: (3, 3)
Форма транспонованого вектора: (10,)
Форма стовпчикового вектора: (10, 1)
Форма транспонованого стовпчикового вектора: (1, 10)
